### ISSUE TITLE
create basic screen Home (page):

### ISSUE THREAD

**Issue by Shifra-fraiman** [Shifra-fraiman/smallBusinessManagementSystem#1]
**components:**
1. **About**- Title and information about service of a small Business managament system.
2. **Button of create bussiness**- **a**. button component, **b**. logic func in the home.

Displaying all the above components on the home screen.

**Comment by ChayaKook** [comment]
the basic component is created.
after, need add links from the current button to the current screens.

**Comment by ChayaKook** [comment]
created

**Comment by ChayaKook** [comment]
V
