### ISSUE TITLE
Create screen Add a business page:

### ISSUE THREAD

**Issue by Shifra-fraiman** [Shifra-fraiman/smallBusinessManagementSystem#3]
**Forms:**
Consists of 3 forms (components?) - Subject types:
**1. Business owner details:** name, email, and so on- must.
**2. Products provided by the business**- option to skip
**3. Meeting times**- choose days and hours - option to skip
(The second two steps can be skipped and changed at any time.)
**4. business created**- When the business is created, the business owner receives routing, and a business number. (component that we will import in the popup)

**Comment by Shifra-fraiman** [comment]
2- This section is incorrect.
Before the product- need the name of bussines, 
or the name in owner details?
oe the name with product?
Now-
1. Business owner details: name, email, and so on- must.
2. Details of the business: name and Meeting times- choose days and hours - option to skip
3. Products provided by the business- option to skip
@ChayaKrashinski ,Am I right in this division?

**Comment by Shifra-fraiman** [comment]
@ChayaKrashinski, What do you think about that?

**Comment by ChayaKook** [comment]
Still relevant?

**Comment by Shifra-fraiman** [comment]
No. I did it, thanks.
